export const nonCarouselBtns = [
	'Dates',
	'Group size',
	'More filters',
];
export const carouselButtons = [
	'Great for groups',
	'Family-friendly',
	'Animals',
	'Arts & writing',
	'Baking',
	'Cooking',
	'Dance',
	'Drinks',
	'Entertainment',
	'Fitness',
	'History & culture',
	'Magic',
	'Music',
	'Social impact',
	'Wellness',
	'Olympians & Paralympians',
	'Designed for accessibility',
	'Magic',
	'Music',
	'Social impact',
	'Wellness',
	'Olympians & Paralympians',
	'Designed for accessibility',
];
